class LocalData {
  static const parentsAgeGroup = {
    "unspecified": 0,
    "<20y": 1,
    "20y-30y": 2,
    "31y-40y": 3,
    "41y-50y": 4,
    ">50y": 5,
  };

  static String findParentsAgeGroupKey(int value) {
    for (final key in parentsAgeGroup.keys) {
      if (parentsAgeGroup[key] == value) {
        // if (key == "unspecified") return "--";
        return key;
      }
    }
    return "--"; // Or throw an exception if the value doesn't exist
  }

  static String findGenderKey(String value) {
    for (final key in genders.keys) {
      if (genders[key] == value) {
        return key;
      }
    }
    return "--";
  }

  static String findDiseaseAgeGroupKey(int value) {
    for (final key in diseaseAgeGroup.keys) {
      if (diseaseAgeGroup[key] == value) {
        return key;
      }
    }
    return "--"; // Or throw an exception if the value doesn't exist
  }

  static const diseaseAgeGroup = {
    "<1y": 0,
    "1y-4y": 1,
    "5y-9y": 2,
    "10y-14y": 3,
    "15y-19y": 4,
    "20y-24y": 5,
    "25y-29y": 6,
    "30y-34y": 7,
    "35y-39y": 8,
    "40y-44y": 9,
    "45y-49y": 10,
    "50y-54y": 11,
    "55y-59y": 12,
    "60y-64y": 13,
    "65y-69y": 14,
    ">70y": 15
  };
  static const genders = {"MALE": "M", "FEMALE": "F"};
  static const barangays = [
    "Abulan",
    "Addalam",
    "Arubub",
    "Bannawag",
    "Bantay",
    "Pob 1",
    "Pob 2",
    "Barangcuag",
    "Dalibubon",
    "Daligan",
    "Diarao",
    "Dibuluan",
    "Dicamay I",
    "Dicamay II",
    "Dipangit",
    "Disimpit",
    "Divinan",
    "Dumawing",
    "Fugu",
    "Lacab",
    "Linamanan",
    "Linomot",
    "Malannit",
    "Minuri",
    "Namnama",
    "Napaliong",
    "Palagao",
    "Papan Este",
    "Papan Weste",
    "Payac",
    "Pungpongan",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Sebastian",
    "San Vicente",
    "Santa Isabel",
    "Santo Domingo",
    "Tupax",
    "Usol",
    "Villa Bello",
  ];

  static final diseases = [
    'ABDOMINAL COLIC (04/92/77)',
    'ABRASION',
    'ABSCESS/CELLULITIS',
    'ACUTE BRONCHITIS',
    'ACUTE CYSTITIS',
    'ACUTE GASTRITIS',
    'ACUTE GASTROENTIRITIS WITH MODERATE DEHYDRATION',
    'ACUTE GLOMERULONEPHRITIS',
    'ACUTE PYELONEPHRITIS',
    'ACUTE RENAL FAILURE',
    'ACUTE ABDOMEN',
    'ACUTE NEPHRITIS',
    'ACUTE TONSILOPHARYNGITIS',
    'ACUTE UPPER RESPIRATORY TRACT INFECTION',
    'ALCOHOL INTOXICATION',
    'ALLERGIC RHINITIS',
    'AMOEBIASIS',
    'ANEMIA;MODERATE',
    'ANGINA PECTORIS',
    'ANGIODERMA',
    'ANIMAL BITE (ALL FORMS)',
    'APPENDICITIS',
    'ARTHRITIS/OSTEOARTHRITIS',
    'AVULSION (ALL FORMS)',
    'BENIGN  PAROXYSMAL POSITIONAL VERTIGO',
    'BENIGN FEBRILE SEIZURE',
    'BENIGN PROSTATIC HYPERTROPHY',
    'BITE (ALL FORMS)',
    'BRONCHIAL ASTHMA IN ACUTE EXACERBATION',
    'BURN  (all forms)',
    'CANCER  (all forms)',
    'BPN-1',
    'CAP/PCAP/BPN',
    'CARBUNCLE',
    'CARDIOVASCULAR Disease',
    'CEREBRAL CONCUSSION  (ALL FORMS)',
    'Cerebrovascular ACCIDENT',
    'CHALAZION',
    'CONSTIPATION',
    'CHOLECYSTITIS',
    'CHOLELITHIASIS',
    'CHRONIC OBSTRUCTIVE PULMONARY DISEASE IN ACUTE EXACERBATION',
    'CHRONIC RENAL FAILURE',
    'CONGESTIVE HEART FAILURE',
    'CONJUNCTIVITIS',
    'CONTUSION',
    'COSTOCHONDRITIS',
    'DENGUE FEBRILE SYNDROME WITH AND WITHOUT WARNING SIGNS',
    'DENTAL CARRIES',
    'DERMATITIS',
    'DYSPEPSIA',
    'EPISTAXIS',
    'ERROR OF REFRACTION',
    'FECAL IMPACTION',
    'ELECTRICAL INJURY (DYSLIPEDEMIA)',
    'EMPHYSEMA (FOLLICULITIS)',
    'FOOD POISONING',
    'FOREIGN BODY',
    'FRACTURE (ALL FORMS)',
    'FUNCTIONAL CONSTIPATION',
    'FUNGAL INFECTION',
    'GASTROESOPHAGIAL REFLUX DISEASE',
    'GENERAL ANXIETY DISORDER',
    'GYNECOMASTIA',
    'HEMORRHOIDS',
    'HORDEOLUM',
    'HYPERCHOLESTEROLEMIA',
    'HYPEREMESIS GRAVIDARUM',
    'HYPERSENSITIVITY REACTION',
    'HYPERTENSION;CONTROLLED',
    'HYPERTENSIVE CARDIOVASCULAR DISEASE',
    'HYPERURECEMIA',
    'HYPOGLYCEMIA',
    'HYPOTENSION',
    'IMPACTED CERUMEN',
    'IMPETIGO',
    'INCOMPLETE ABORTION',
    'INFLUENZA',
    'INGUINAL HERNIA',
    'INTESTINAL OBSTRUCTION/ILEUS OBSTRUCTION',
    'ISCHEMIC HEART DISEASE',
    'LIVER DISEASE',
    'LYMPHADENITIS',
    'COVID-19',
    'MEASLES',
    'MULTIPLE PHYSICAL INJURIES 2° VEHICULAR ACCIDENT',
    'MUMPS',
    'MUSCULOSKELETAL DISORDER (LUMBAR)',
    'MYOCARDIAL INFARCTION',
    'MSS (MYALGIA)',
    'NEURITIS',
    'NEPHROLITHIASIS',
    'NIDDM/DM TYPE 2',
    'OMPHOLITIS',
    'ORAL CANDIDIASIS',
    'OTITIS MEDIA',
    'PAROTITIS',
    'PEPTIC ULCER DISEASE',
    'PHYSICAL INJURY SECONDARY TO FALL',
    'PPSR',
    'PRE-ECLAMPSIA/ECLAMPSIA',
    "PULMONARY TUBERCULOSIS/PRIMARY KOCK'S INFECTION",
    'RENAL STONE',
    'SEPSIS',
    'SINUSITIS',
    'SOFT TISSUE INJURY SECONDARY TO MAULING',
    'STOMATITIS',
    'SYNDACTYL',
    'SYSTEMIC VIRAL ILLNESS',
    'TENDONITIS',
    'TENSION HEADACHE',
    'THREATENED ABORTION (ABUSE)',
    'THYPHOID FEVER',
    'TINEA CULPURIS (TOOTH EXTRACTION)',
    'UNKNOWN',
    'UPPER GASTROINTESTINAL BLEEDING',
    'URINARY TRACT INFECTION',
    'UROLITHIASIS',
    'URTICARIA',
    'VARICELLA',
    'VIRAL EXANTHEM',
    'WOUNDS (ALL FORMS)',
    'FOOT AND MOUTH DISEASE',
    'CIRCUMCISION'
  ];

  static final mortalityDisease = [
    'ACUTE  MYOCARDIAL INFARCTION',
    'CEREBROVASCULAR ACCIDENT (CVA); HIGH RISK',
    'CHRONIC OBSTRUCTIVE PULMONARY DISEASE (COPD); SEVERE',
    'COMMUNITY ACQUIRED PNEUMONIA (SEVERE)',
    'HEMORRHAGIC SHOCK',
    'PROBABLE END CHRONIC RENAL FAILURE',
    'CANCER (ALL FORMS)',
    'LIVER CIRRHOSIS',
    'HEMORRHAGIC STROKE',
    'ASPHYXIA SECONDARY TO DROWNING',
    'PROBABLE SEPTICEMIA',
    'ANEMIA; SEVERE',
    'STATUS ASTHMATICUS',
    'STATUS EPILEPTICUS',
    'PROBABLE CONGESTIVE HEART FAILURE',
    'MULTIORGAN FAILURE',
    'PROBABLE CARDIAC ARRYTHMIA',
    'HEPATIC ENCEPHALOPATHY',
    'HYPOVOLEMIC SHOCK SECONDARY TO STABBED WOUND',
    'PROBABLE HEMORRHAGIC SHOCK SECONDARY TO BLUNT ABDOMINAL TRAUMA SECONDARY TO FALL',
  ];
}
